### ISSUE TITLE
Error when running `todo`

### ISSUE THREAD

**Issue by santib** [juanmanuelramallo/todo#1]
```
➜  $ todo
Traceback (most recent call last):
	7: from /Users/santib/.gem/ruby/2.6.6/bin/todo:23:in `<main>'
	6: from /Users/santib/.gem/ruby/2.6.6/bin/todo:23:in `load'
	5: from /Users/santib/.gem/ruby/2.6.6/gems/todo_cli_app-0.1.0/exe/todo:14:in `<top (required)>'
	4: from /Users/santib/.gem/ruby/2.6.6/gems/todo_cli_app-0.1.0/exe/todo:14:in `new'
	3: from /Users/santib/.gem/ruby/2.6.6/gems/todo_cli_app-0.1.0/lib/session.rb:27:in `initialize'
	2: from /Users/santib/.gem/ruby/2.6.6/gems/todo_cli_app-0.1.0/lib/session.rb:39:in `prepare_todo_file'
	1: from /Users/santib/.gem/ruby/2.6.6/gems/todo_cli_app-0.1.0/lib/session.rb:39:in `open'
/Users/santib/.gem/ruby/2.6.6/gems/todo_cli_app-0.1.0/lib/session.rb:40:in `block in prepare_todo_file': private method `binding' called for #<ToDo::Session:0x00007f8eac0e7918> (NoMethodError)
```

**Comment by santib** [comment]
When running it a second time, it worked 🤔

**Comment by juanmanuelramallo** [comment]
It's an easter egg, second time is the charm, not third's

Maybe I should update to use `send(:binding)` instead of just `binding`, or maybe a different way
